// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH-_CZWQ2lEwwIiulKV2tLkyp4wudtMwU',
    appId: '1:817185446546:web:834c8fb4e84fc3fb7e244b',
    messagingSenderId: '817185446546',
    projectId: 'red-hawk-wallet-dev',
    authDomain: 'red-hawk-wallet-dev.firebaseapp.com',
    storageBucket: 'red-hawk-wallet-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_pqs3TGT0J-0e-Mo62GDI3cipjUgKqHE',
    appId: '1:817185446546:android:cd17833d44899c297e244b',
    messagingSenderId: '817185446546',
    projectId: 'red-hawk-wallet-dev',
    storageBucket: 'red-hawk-wallet-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwELwyyfWOv04vHQC2vq98TH1ayVJ1VjI',
    appId: '1:817185446546:ios:647d6183271e0d747e244b',
    messagingSenderId: '817185446546',
    projectId: 'red-hawk-wallet-dev',
    storageBucket: 'red-hawk-wallet-dev.firebasestorage.app',
    iosBundleId: 'com.example.redhawkwalletFlutter',
  );
}
