import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    final bool fromRegister = GoRouterState.of(context).extra == 'register';

    return Scaffold(
      appBar: AppBar(title: const Text('Privacy Policy')),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _header('Red Hawk Wallet — Privacy Policy', cs),
                  _meta('Version 1.0 · Effective July 1, 2026', cs),
                  const SizedBox(height: 20),
                  _section('1. Information We Collect', cs),
                  _body(
                    'We collect information you provide when registering (name, email, role), information generated by your use of the service (transactions, wallet balance, offers redeemed), and device information (OS version, app version) for debugging.',
                    cs,
                  ),
                  _section('2. How We Use Your Information', cs),
                  _body(
                    'We use your information to operate the wallet, process payments, verify university affiliation, send you relevant offers, and improve the service. We do not sell your personal data.',
                    cs,
                  ),
                  _section('3. Firebase and Google Services', cs),
                  _body(
                    'Red Hawk Wallet uses Firebase Authentication for account management, Cloud Firestore for data storage, and Firebase Storage for media. These services are governed by Google\'s Privacy Policy.',
                    cs,
                  ),
                  _section('4. Payment Information', cs),
                  _body(
                    'Payment card details are processed by Stripe and are never stored on Red Hawk Wallet servers. Stripe\'s privacy policy governs the handling of card data.',
                    cs,
                  ),
                  _section('5. Data Sharing', cs),
                  _body(
                    'We share transaction data with the relevant vendor to fulfill your payment. We do not share personal data with third parties for advertising purposes. We may share data with law enforcement when required by law.',
                    cs,
                  ),
                  _section('6. Data Retention', cs),
                  _body(
                    'Account data is retained while your account is active. Transaction records are retained for a minimum of 7 years for accounting compliance. You may request account deletion, which will anonymize personal data while retaining transaction records.',
                    cs,
                  ),
                  _section('7. Security', cs),
                  _body(
                    'We implement industry-standard security measures including encrypted data in transit (TLS), Firebase security rules, and server-side payment validation. During the beta period, no real funds are at risk.',
                    cs,
                  ),
                  _section('8. Your Rights', cs),
                  _body(
                    'You have the right to access, correct, or delete your personal data. Contact us at privacy@redhawkwallet.com to exercise these rights.',
                    cs,
                  ),
                  _section('9. Children\'s Privacy', cs),
                  _body(
                    'Red Hawk Wallet is not directed to individuals under 18. We do not knowingly collect personal information from minors.',
                    cs,
                  ),
                  _section('10. Changes to This Policy', cs),
                  _body(
                    'We may update this Privacy Policy periodically. We will notify you of material changes via email or in-app notification.',
                    cs,
                  ),
                  _section('11. Contact', cs),
                  _body(
                    'For privacy questions, contact privacy@redhawkwallet.com.',
                    cs,
                  ),
                  const SizedBox(height: 8),
                ],
              ),
            ),
          ),
          if (fromRegister)
            SafeArea(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(20, 12, 20, 16),
                child: SizedBox(
                  width: double.infinity,
                  child: ElevatedButton(
                    onPressed: () => context.pop(),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: cs.primary,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(vertical: 14),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                    child: const Text('I Understand', style: TextStyle(fontSize: 15, fontWeight: FontWeight.w600)),
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _header(String text, ColorScheme cs) =>
      Text(text, style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: cs.onSurface, height: 1.3));

  Widget _meta(String text, ColorScheme cs) =>
      Padding(
        padding: const EdgeInsets.only(top: 4),
        child: Text(text, style: TextStyle(fontSize: 12, color: cs.onSurface.withValues(alpha: 0.5))),
      );

  Widget _section(String text, ColorScheme cs) =>
      Padding(
        padding: const EdgeInsets.only(top: 20, bottom: 6),
        child: Text(text, style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: cs.onSurface)),
      );

  Widget _body(String text, ColorScheme cs) =>
      Text(text, style: TextStyle(fontSize: 13, color: cs.onSurface.withValues(alpha: 0.75), height: 1.7));
}
